FROM ubuntu:16.04

LABEL maintainer="Ian Martin <ian@imartin.net>" license="MIT" description="Distributed NodeJS app for automated ripping and encoding media"
ENV DISPLAY=":0" LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive NODE_ENV=development U=ncodr

RUN echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial universe \
  deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates universe \
  deb http://us.archive.ubuntu.com/ubuntu/ xenial multiverse \
  deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates multiverse" >> /etc/apt/sources.list && \
  echo 'deb http://ppa.launchpad.net/heyarje/makemkv-beta/ubuntu xenial main' > /etc/apt/sources.list.d/makemkv.list && \
  echo 'deb http://ppa.launchpad.net/stebbins/handbrake-releases/ubuntu xenial main' > /etc/apt/sources.list.d/handbrake.list && \
  echo "deb http://deb.nodesource.com/node_8.x xenial main" > /etc/apt/sources.list.d/nodejs.list && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8771ADB0816950D8 && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8540356019f7e55b && \
  apt-key adv --fetch-keys http://deb.nodesource.com/gpgkey/nodesource.gpg.key && \
  apt-get -qq update && \
  apt-get install -yq makemkv-oss makemkv-bin curl libav-tools libbluray-bin lsdvd dvdbackup libdvd-pkg handbrake-cli nodejs && \
  dpkg-reconfigure libdvd-pkg && \
  apt-get clean && \
  groupadd -fg 10298 ${U} && \
  useradd --create-home --uid 10298 --gid ${U} ${U} && \
  passwd -l ${U} && \
  mkdir -p /media /rips /ncodr && \
  chown -R 10298:10298 /media /rips && \
  chmod 4755 /usr/bin/bd_info

USER ${U}
EXPOSE 2000
WORKDIR /ncodr
VOLUME ['/media','/ncodr']
ENTRYPOINT ["/usr/bin/npm"]
CMD ["run", "serve"]
