---
name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get app version
        run: |
          echo "APP_VERSION=$(yarn run --silent version)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build feature branch
        uses: docker/build-push-action@v5
        if: github.event_name == 'pull_request'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          load: true
          # if we wanted to integration test the image, we could run it here. load=true means that the build output will be the local docker
          # daemon. So the image will be available after this step, and could be pushed later with another call to docker/build-push-action, which
          # would use the cache from this step, so it would be fast.
          tags: ${{ github.repository }}:${{ github.event.pull_request.head.ref }}
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VCS_REF=${{ github.event.pull_request.head.sha }}
            VERSION=${{ env.APP_VERSION }}
          # use cache from PR branch, but fall back to main branch if not found
          cache-from: |
            type=gha
            type=gha,scope=main
          cache-to: type=gha,mode=max

      - name: Build and push latest
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:latest
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VCS_REF=${{ github.ref }}
            VERSION=${{ env.APP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push tagged version
        uses: docker/build-push-action@v5
        if: github.ref_type == 'tag'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VCS_REF=${{ github.ref_name }}
            VERSION=${{ env.APP_VERSION }}
          cache-from: type=gha,scope=main
          cache-to: type=gha,mode=max
