---
name: Testing
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: 'package.json'
          cache-dependency-path: 'yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run linter
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: 'package.json'
          cache-dependency-path: 'yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: unittests
